### ISSUE TITLE
Add Updated "Dracoon" API

### ISSUE THREAD

**Issue by Kurainu** [APIs-guru/openapi-directory#625] opened 2019-11-08 22:27 UTC
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://dracoon.team/api/spec_v4/
**Name**: Dracoon

**Comment by MikeRalphson** [comment] 2019-11-26 11:49
```
Swagger schema validation failed. 
  Data does not match any schemas from 'anyOf' at #/definitions/UserUserPublicKeyList/properties/items/items
    Additional properties not allowed: originalRef at #/definitions/UserUserPublicKeyList/properties/items/items
    Expected type array but found type object at #/definitions/UserUserPublicKeyList/properties/items/items
```

**Comment by MikeRalphson** [comment] 2019-11-26 12:00
Your API description would have been updated automatically, except for the validation errors above.

**Comment by Kurainu** [comment] 2019-11-27 20:12
Thats the offical API from Dracoon and i cannot fix the validation errors if want and could. if you can't update the api with this validation errors the issue can be closed.

**Comment by MikeRalphson** [comment] 2019-12-05 16:36
Have contacted Dracoon to see if they can fix.

**Comment by dracoon-admin** [comment] 2020-02-26 15:34
Thanks for the report. I can confirm the validation issue. Most validation issues will be resolved with the next release. However, two validation issues will still remain until we migrate to OpenAPI 3.0 (because we need OAuth URIs to be relative and relative URIs in general are only supported in OpenAPI 3.0).

I will update this issue after we have migrated to OpenAPI 3.0.

**Comment by MikeRalphson** [comment] 2020-03-23 13:28
v4.18.1 of the Dracoon API definition passes our validators. Thanks all.

**Closed by MikeRalphson** 2020-03-23 13:28 UTC
Labels: Blocked by errors in source definition, waiting for response
