### ISSUE TITLE
Add "Load To Truck Ratio" API

### ISSUE THREAD

**Issue by andriykudelya** [APIs-guru/openapi-directory#651] opened 2019-11-19 18:35 UTC
**Format**: API Blueprint
**Official**: YES
**Url**: https://www.loadtotruck.app/documentation
**Name**: Load To Truck Ratio

**Comment by MikeRalphson** [comment] 2019-11-26 11:43
Duplicate of #653

**Closed by MikeRalphson** 2019-11-26 11:43 UTC
