### ISSUE TITLE
Add "GazeCloudAPI" API

### ISSUE THREAD

**Issue by szydej** [APIs-guru/openapi-directory#818] opened 2021-04-15 14:01 UTC
**Format**: 
**Official**: 
**Url**: https://api.gazerecorder.com
**Name**: GazeCloudAPI
**Category**: analytics
**Logo**: https://api.gazerecorder.com/favicon.png

**Comment by MikeRalphson** [comment] 2021-04-15 15:20
Duplicate of #761

**Closed by MikeRalphson** 2021-04-15 15:20 UTC
