### ISSUE TITLE
Add "Grid Dispatch (Green Energy Distribution API)" API

### ISSUE THREAD

**Issue by zoernert** [APIs-guru/openapi-directory#766] opened 2021-01-02 01:39 UTC
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://corrently.io/dist.yaml
**Name**: Grid Dispatch (Green Energy Distribution API)

**Comment by MikeRalphson** [comment] 2021-01-02 10:00
Looks like a dupe of #765

**Closed by MikeRalphson** 2021-01-02 10:00 UTC
