### ISSUE TITLE
Add "Universal Facial Recognition" API

### ISSUE THREAD

**Issue by datachipio** [APIs-guru/openapi-directory#799] opened 2021-03-24 09:38 UTC
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://faceidentity-beta.azurewebsites.net/api/v1.0.0/swagger-ui.html
**Name**: Universal Facial Recognition
**Category**: monitoring
**Logo**: https://www.datachip.io

**Comment by MikeRalphson** [comment] 2021-03-31 13:27
Duplicate of #795

**Closed by MikeRalphson** 2021-03-31 13:27 UTC
