### ISSUE TITLE
Add "Solcast" API

### ISSUE THREAD

**Issue by Mankucic** [APIs-guru/openapi-directory#1081] opened 2022-12-15 22:51 UTC
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://solcast.com
**Name**: Solcast
**Category**: monitoring
**Logo**: https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.solcast.com%2Fuploads%2FSolcast%2520API%2520Toolkit%2520-%2520Small.png&imgrefurl=https%3A%2F%2Fsolcast.com%2Fblog%2Fsolar-data-api%2Fapi-toolkit-launch-makes-accessing-solar-data-easier-than-ever&tbnid=lN1j_3TakVgToM&vet=12ahUKEwib_6Su2vz7AhXf83MBHWnGBHMQMygBegUIARC4AQ..i&docid=Mlvh8NC-QyhBPM&w=720&h=288&itg=1&q=solcast&ved=2ahUKEwib_6Su2vz7AhXf83MBHWnGBHMQMygBegUIARC4AQ

**Comment by MikeRalphson** [comment] 2023-03-04 13:09
Closing as looks like a dupe of #1092

**Closed by MikeRalphson** 2023-03-04 13:09 UTC
