### ISSUE TITLE
Add "Telenor " API

### ISSUE THREAD

**Issue by Amir9279** [APIs-guru/openapi-directory#794] opened 2021-03-21 08:52 UTC
**Format**: 
**Official**: YES
**Url**: https://www.telenor.com.pk/help-support/
**Name**: Telenor 
**Category**: social
**Logo**:

**Comment by MikeRalphson** [comment] 2021-03-31 13:28
Duplicate of #793

**Closed by MikeRalphson** 2021-03-31 13:28 UTC
