### ISSUE TITLE
Add "TollGuru Toll REST" API

### ISSUE THREAD

**Issue by Nickonomics** [APIs-guru/openapi-directory#772] opened 2021-01-07 13:51 UTC
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://dev.api.tollguru.com/calc/documentation
**Name**: TollGuru Toll REST

**Comment by MikeRalphson** [comment] 2021-01-07 14:49
Looks like a dupe of #770

**Closed by MikeRalphson** 2021-01-07 14:49 UTC
