### ISSUE TITLE
Add "Newsdata.io API" API

### ISSUE THREAD

**Issue by digitalrajat** [APIs-guru/openapi-directory#874] opened 2021-09-23 06:42 UTC
**Format**: WADL
**Official**: YES
**Url**: https://newsdata.io/
**Name**: Newsdata.io API
**Category**: media
**Logo**: https://newsdata.io/images/global/newsdata-icon.png

**Comment by MikeRalphson** [comment] 2022-08-26 09:59
Dupe of #869

**Closed** 2022-08-26 10:00 UTC
Labels: add API
