### ISSUE TITLE
Add "event tickets search" API

### ISSUE THREAD

**Issue by Bizstats** [APIs-guru/openapi-directory#549] opened 2019-03-11 10:56 UTC
**Format**: Google API Discovery
**Official**: YES
**Url**: https://www.bizstats.ai/api/event_tickets
**Name**: event tickets search

**Comment by MikeRalphson** [comment] 2019-03-12 16:50
Link 404s and looks like a dupe of #550

**Closed by MikeRalphson** 2019-03-12 16:50 UTC
