### ISSUE TITLE
Add "TagTeam" API

### ISSUE THREAD

**Issue by Hannahroseoc** [APIs-guru/openapi-directory#952] opened 2022-01-17 04:25 UTC
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://tagteam.ai/
**Name**: TagTeam
**Category**: machine_learning
**Logo**:

**Comment by MikeRalphson** [comment] 2022-08-26 09:29
Dupe of #954

**Closed by MikeRalphson** 2022-08-26 09:29 UTC
Labels: add API
