### ISSUE TITLE
Add "Universal Facial Recognition API" API

### ISSUE THREAD

**Issue by datachipio** [APIs-guru/openapi-directory#798] opened 2021-03-23 09:06 UTC
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://faceidentity-beta.azurewebsites.net/api/v1.0.0/swagger-ui.html
**Name**: Universal Facial Recognition API
**Category**: monitoring
**Logo**: https://www.datachip.io

**Comment by datachipio** [comment] 2021-03-24 06:18
API Overview
DataChip’s – Universal Facial Recognition API provides a platform for enterprises to implement Facial Recognition into their applications with ease. Developers have the flexibility to choose our API between Azure, AWS, and DataChip API, and its versatility enables developers to integrate High Accuracy Face Recognition APIs with only a few lines of code.
Technical Highlights
Our API reliably detects and identify human faces accurately
Ease of switching between AWS, Azure API, and DataChip API’s  
Easily support Cloud-based Facial recognition or on-premise and Edge-based processing 
Easy to use – Add our API to your application through a single API call
APIs are platform-independent, language-independent, standards-based (runs on top of HTTPS), and can be used in the presence of firewalls
Use case
Attendance Management – Non-Contact facial recognition in Attendance management enables you to safeguard your work environment and increases productivity 
Health Care –Identification of patients, especially during emergencies 
Retail – During shopping, retrieving the customer’s name able to enhance their shopping experience and also able to prevent retail crime
Identify missing persons - Face recognition can be used to find missing children and victims of human trafficking. 
Protect school from threats - Identify when expelled students, dangerous parents, or other individuals that pose a threat to school safety enter school grounds. 
Control Access to sensitive areas - Face recognition can work as a means of access control to ensure that only authorized individuals get into facilities 
Protect law enforcement - Helps authorities instantly identify individuals in the field from a safe distance. This approach tells them whom they are dealing with and whether they need to proceed with caution
For Secure Transactions – Using facial recognition, users can make their payment transaction by scanning their faces

**Comment by MikeRalphson** [comment] 2021-03-31 13:27
Duplicate of #795

**Closed by MikeRalphson** 2021-03-31 13:27 UTC
