### ISSUE TITLE
Add "OrderCloud.io" API

### ISSUE THREAD

**Issue by eerickson451** [APIs-guru/openapi-directory#117] opened 2016-09-26 19:45 UTC
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/ordercloud-api/swagger/master/ordercloud_swagger.json
**Name**: OrderCloud.io

**Comment by IvanGoncharov** [comment] 2016-09-27 21:45
@eerickson451 Thank you for submission.
I found few errors in your spec, see here:
http://editor.swagger.io/#/?import=https://raw.githubusercontent.com/ordercloud-api/swagger/master/ordercloud_swagger.json
This tool is laggy so you need to wait for a couple of seconds.

Can you please fix them?
The most frequent issue, is very simple and caused by parameters like that:
```json
          {
            "name": "filters",
            "in": "query",
            "description": "Any additional key/value pairs passed in the query string are interpretted as filters. Valid keys are top-level properties of the returned model or 'xp.???'",
            "required": false,
            "type": "object"
          }
```
Problem is that OpenAPI doesn't support `object` as type for query parameters:
> Since the parameter is not located at the request body, it is limited to simple types (that is, **not an object**). The value MUST be one of "string", "number", "integer", "boolean", "array" or "file". 

For more details see this:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#user-content-parameterType

You can fix this by simply replacing `object` with `string`, it correct solution since any `query` parameter can be passed as a string.

**Comment by MikeRalphson** [comment] 2017-03-17 22:54
Ping @eerickson451 are you still working on resolving the errors in this definition?

**Comment by tmenier** [comment] 2017-03-27 15:09
@MikeRalphson eerickson451 is no longer responsible for this but we're transitioning it to someone else to look into soon. Hope you don't mind leaving this open a bit longer. Thanks!

**Comment by MikeRalphson** [comment] 2018-05-03 08:59
Closing due to inactivity - but please feel free to reopen the issue if necessary.

**Closed by MikeRalphson** 2018-05-03 08:59 UTC
Labels: waiting for response
