### ISSUE TITLE
Add "P4e-OTPAdminApis" API

### ISSUE THREAD

**Issue by fedexp4e** [APIs-guru/openapi-directory#694] opened 2020-05-06 09:05 UTC
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: NO
**Url**: https://api.jsonbin.io/b/5eb27a8147a2266b1473ab3b
**Name**: P4e-OTPAdminApis

**Comment by MikeRalphson** [comment] 2020-05-06 09:10
Duplicate of #693

**Closed by MikeRalphson** 2020-05-06 09:10 UTC
