### ISSUE TITLE
Add "COVID-19 Vaccine Status For Brasil" API

### ISSUE THREAD

**Issue by alavenimahender** [APIs-guru/openapi-directory#812] opened 2021-04-09 11:37 UTC
**Format**: OpenAPI 3.0
**Official**: 
**Url**: https://vaccinationstatus.azurewebsites.net/covid-vaccine-status/v1.0.0/swagger-ui.html , https://vaccinationstatus.azurewebsites.net/covid-vaccine-status/v1.0.0/brasil/api/swagger-ui.html
**Name**: COVID-19 Vaccine Status For Brasil
**Category**: monitoring
**Logo**: https://www.datachip.io

**Comment by MikeRalphson** [comment] 2021-04-09 12:08
Duplicate of #811

**Closed by MikeRalphson** 2021-04-09 12:08 UTC
