### ISSUE TITLE
Add "TollGuru Toll REST" API

### ISSUE THREAD

**Issue by Nickonomics** [APIs-guru/openapi-directory#771] opened 2021-01-07 13:50 UTC
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: blob:https://dev.api.tollguru.com/5675aaa8-1664-4d07-ba22-dea1ccf75555
**Name**: TollGuru Toll REST

**Comment by MikeRalphson** [comment] 2021-01-07 14:49
Looks like a dupe of #770

**Comment by Nickonomics** [comment] 2021-01-07 18:14
Hey Mike, here is the link for the API definition.
blob:https://dev.api.tollguru.com/5675aaa8-1664-4d07-ba22-dea1ccf75555

Thank you taking this up.

**Comment by MikeRalphson** [comment] 2021-01-07 18:23
Thanks, but I get `{"message":"Forbidden"}` when I try to access that URL.

**Comment by MikeRalphson** [comment] 2021-01-07 18:25
Please can we continue on just one issue, #770

**Closed by MikeRalphson** 2021-01-07 18:25 UTC
Labels: waiting for response
