### ISSUE TITLE
Add "Intelligent Automation (OCR, AI,...)" API

### ISSUE THREAD

**Issue by HanneContractFit** [APIs-guru/openapi-directory#598] opened 2019-08-21 15:16 UTC
**Format**: Swagger 2.0
**Official**: YES
**Url**: https://cfportal.contract-p.fit/swagger.json
**Name**: Intelligent Automation (OCR, AI,...)
**Valid**: No

**Comment by MikeRalphson** [comment] 2019-09-02 08:47
Hi, thanks for the contribution. At your given URL I get an error message:

{"error":"Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}

**Comment by HanneContractFit** [comment] 2019-09-02 10:01
Hi Mike,

Is this better: https://cfportal.contract-p.fit/apidoc/ 
That's our Swagger, but I thought you needed the base-URL. 

This is another url I found: https://cfportal.contract-p.fit/swagger.json

Is one of these 2 okay?

**Comment by MikeRalphson** [comment] 2019-09-02 10:12
Thanks, it's the `swagger.json` URL we need.

Unfortunately there's some validation errors in your definition, could you look at fixing these before inclusion?

https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fcfportal.contract-p.fit%2Fswagger.json

```yaml
---
messages:
- "attribute definitions.EvaluationDataPost.definitions is unexpected"
- "attribute definitions.EvaluationDataPost.patternProperties is unexpected"
schemaValidationMessages:
- level: "error"
  domain: "validation"
  keyword: "additionalProperties"
  message: "object instance has properties which are not allowed by the schema: [\"\
    definitions\",\"patternProperties\"]"
  schema:
    loadingURI: "http://swagger.io/v2/schema.json#"
    pointer: "/definitions/schema"
  instance:
    pointer: "/definitions/EvaluationDataPost"
  required: null
  missing: null
```

**Comment by MikeRalphson** [comment] 2019-09-02 10:16
Is this a different API, or is this issue a dupe of #576?

**Comment by HanneContractFit** [comment] 2019-09-02 11:12
Ah yes, it's a duplicate. Sorry.

I will ask our technical people to take a look at the screenshot you just sent! Sorry for the confusion.

**Comment by MikeRalphson** [comment] 2020-07-13 13:20
Responding with status code `500`.

**Comment by MikeRalphson** [comment] 2020-08-25 08:09
API added, many thanks for the contribution!

**Closed by MikeRalphson** 2020-08-25 08:09 UTC
Labels: add API
